### ISSUE TITLE
Some bugs and feature requests on new bot

### ISSUE THREAD

**Issue by AliM1988** [diditra/x-ui#3] opened 2023-03-18 12:42 UTC
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

bugs that I see:
1. In TG Clients section **Enabled** button on TG Clients doesn't work.
2. In TG Clients section **Email** field is empty and doesn't show anything.
3. When I enable the Telegram CRM, it won't save.

feature requests:
1. Send notification to clients when expire time is less than N days or remaining traffic is less than N gigabyte.
2. Add menu to bot (instead default menu)

**Comment by diditra** [comment] 2023-03-19 20:22
Thanks for checking out the panel. Here are my comments.

Bugs:
1- Yes that enabled button for TG clients is not working yet. Will make it read only in the next release.
2- If you enable "Telegram CRM" from settings, then your users can order new accounts via the bot. During registration they will be asked to enter their email. But for the users that already have an account and register themselves by checking their usage the email field remains blank.
3- I can't reproduce this bug. Is it a clean install or upgrade? Can you try with a clean install?

Feature requests:
1- It's already on my list. Right now I'm working on the central_panel branch.
2- Do you mean one of those permanent menus that opens at the bottom of the screen in the bot? Do you have a screenshot of something similar?

**Comment by AliM1988** [comment] 2023-03-19 23:23
> 

Thank you for your reply. So,

Bugs:
1. OK
2. I thought Email field refer to Email in clients section. So it would good if you add new column to show client's email as "client name".
3. It is Upgrade. I have the database already. When I delete x-ui.db, Telegram CRM can be saved. But I lost current database if I want to have CRM.

(New) Feature requests:
2-Yes, I mean permanent menus. Unfortunately I have not screenshot.
3- I suggest that allow admin to edit TG clients from panel or add new record to it. I can edit/add records of x-ui-tg.db manually, but it would be great that it can be done from panel.
4-Is it possible one telegram account links to multiple UUID ?

regard

**Comment by AliM1988** [comment] 2023-04-11 00:25
@diditra 
Thank you for implantation sending reminder to clients. There are some comments:
1. When expiration time is null [unlimited], it send reminder.
2. Please change Active: true/false  to  Yes/No
3. Please hide support menu while CRM is inactive.

**Comment by diditra** [comment] 2023-04-15 07:54
Hi,

1- It's fixed in v1.1.3.
2- OK!
3- Support is actually the only way for the user to contact you from the bot. You can customize the message under the CRM settings and put whatever you like there such as your Telegram ID.

**Closed** 2023-04-15 20:15 UTC
